// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _add_YADSCCostCenters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_YADSCCostCenters));
        
        string IMigrationMetadata.Id
        {
            get { return "202010280639352__add_YADSCCostCenters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
